### ISSUE TITLE
<Link> onClick firing on page load

### ISSUE THREAD

**Issue by sashahilton00** [Shopify/polaris-react#1091] opened 2019-02-25 16:31 UTC
# Issue summary

When specifying an onClick handler to the Link component, the handler fires on page load.

## Expected behavior

Handler only fires when component is clicked.

## Actual behavior

Handler fires on page load.

## Steps to reproduce the problem

1. See text case below. We are using react-saga, hence relevant action is wrapped in `mapDispatchToProps`

## Reduced test case

```
<Card.Header title="Card Header">
	<TextStyle variation="strong">Example Link:</TextStyle>
	<Link onClick={this.props.clickHandler}>Test Link</Link>
</Card.Header>
...
const mapDispatchToProps = (dispatch) => {
  return {
    clickHandler: (id) => dispatch({ type: 'ROUTE_EXAMPLE', payload: { id } })
  }
}
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.6.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System: OS X 10.13.6

**Comment by AndrewMusgrave** [comment] 2019-02-25 16:41
Hi @sashahilton00 , are you providing `AppProvider` with a custom `linkComponent`?

**Comment by sashahilton00** [comment] 2019-02-26 15:20
Nope, here's the code we're using to initialise things:

```
ReactDOM.render(
  <Provider store={store}>
    <AppProvider>
      <App />
    </AppProvider>
  </Provider>,
  rootEl
)
```
where the `{store}` is just the bog standard returned value from redux `createStore`

**Comment by AndrewMusgrave** [comment] 2019-02-27 18:05
I can't reproduce this or see anything that would cause this bug, we're passing the handler straight to the dom element. Do you have an example that reproduces this?

**Comment by sashahilton00** [comment] 2019-02-27 22:34
Sure, here's an abbreviated version of the problematic component:

```
import React, { Component } from 'react'
import { Card, Layout, Link, Page, TextStyle } from '@shopify/polaris'

import {connect} from 'react-redux'

class Customer extends Component {

  state = {
    showHelp: false,
    }
  };

  render() {
    const { showHelp } = this.state;

    const rbMarkup = (
      <>
        <TextStyle variation="strong">RB: </TextStyle>
        <Link onClick=this.props.viewCustomer>{ customer.rb.firstName }</Link>
      </>
    );

    const customerDetails = (
      <Card>
        <Card.Header title="Customer Details">
          {rbMarkup}
        </Card.Header>
        <Card.Section>
          ...
        </Card.Section>
      </Card>
    )

    ...
    
    return(
      <Page
        fullWidth
        title={`Customer - ${customer.firstName}`}
        secondaryActions={[
          {
            content: "Getting Started",
            disabled: false,
            icon: 'circleInformation',
            onAction: () => {
              this.setState({ showHelp: !showHelp })
            }
          }
        ]}
      >
        <Layout>
          <Layout.Section>
            {customerDetails}
          </Layout.Section>
          <Layout.Section secondary>
            ...
          </Layout.Section>
        </Layout>
      </Page>
    )
  }

}

const mapStateToProps = (state) => {
  return { state }
}

const mapDispatchToProps = (dispatch) => {
  return {
    viewCustomer: (id) => dispatch({ type: 'ROUTE_CUSTOMER', payload: { id } })
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Customer);
```
the problematic line is the `<Link>` one in the above example. If it is changed to the below, it works fine:
```
<Link onClick={ () => {this.props.viewCustomer(customer.rb._id)} }>{ customer.rb.firstName }</Link>
```

**Comment by AndrewMusgrave** [comment] 2019-03-01 16:07
I still seem unable to reproduce the bug with your code sample ([here's the working example](https://codesandbox.io/s/p5j2q6xo3j)). Is it possible you'r dispatching an action with the same type elsewhere?

**Comment by AndrewMusgrave** [comment] 2019-03-06 21:24
I'm going to close the issue for now. Please feel free to re-open if this persists.

**Closed by AndrewMusgrave** 2019-03-06 21:24 UTC
