### ISSUE TITLE
[Button] Add “pressed” state

### ISSUE THREAD

**Issue by vinay30** [Shopify/polaris-react#687] opened 2018-11-28 05:18 UTC
## Problem

Sometimes buttons are used as a radio button, usually in a button group with segmented buttons but potentially on their own (as a toggle).

This has been implemented in polaris-rails: https://github.com/Shopify/polaris-ux/issues/58

## Examples

<img width="315" alt="screen shot 2017-10-12 at 6 21 06 pm" src="https://user-images.githubusercontent.com/804014/31557049-5590d798-b015-11e7-92a0-bc040d5d19af.png">

Re-created from the previous polaris-react repo.

**Comment by chloerice** [comment] 2018-11-28 19:32
Thanks for bringing this feature request over @vinay30! 

I’ll close this issue for now, as we treat all feature requests as part of our backlog. We encourage everyone who wants this feature to add a 👍 to the original issue report. We take your collective interest into account when we look at what to work on next. In the meantime, PRs are always welcome 😊.

**Comment by BPScott** [comment] 2018-11-28 20:44
A few weeks ago I had somebody in Slack ask about a pattern that would have been solved by press states. So this sounds like a good idea to cover user needs.

**Comment by maxariss** [comment] 2018-11-30 17:02
Another 1+ from me ! 

We need this for the RTE toolbar buttons (ex. pressing "bold" and leaving the button in it's "pressed state". Currently we're getting around this by styling the `button` element directly in a wrapped div, but this still presents accessibility issues, as we're missing the `aria-pressed` attribute.

**Comment by danrosenthal** [comment] 2018-11-30 17:08
We'd welcome a PR adding this state. It's already supported in [Polaris rails](https://polaris-rails.shopify.com/components/button#pressed-button) and should be here as well.

**Comment by yourpalsonja** [comment] 2019-04-23 23:52
Hey @elizabethletourneau, we've got a component in `polaris-next` in `web` called `ToggleButton` that has `pressed` state styling and props, based on a few requests and a11y issues. If you're working on adding a `pressed` state to button, it might be best to hop in a meeting with Ryan Fredrick and we can chat about the best way to move forward with this–it might be about getting `ToggleButton` into Polaris as a component, rather than adding a `pressed` state to `Button`.

**Comment by danrosenthal** [comment] 2019-08-19 14:19
Closing as a duplicate of #877

**Closed by danrosenthal** 2019-08-19 14:19 UTC
Labels: ⚗️ Development, 🎨 Design
