### ISSUE TITLE
Textfield of type number

### ISSUE THREAD

**Issue by AKarmanov** [Shopify/polaris-react#2755] opened 2020-02-18 23:13 UTC
## Issue summary
It is impossible to supply a number to a textfield of type number, it takes a string.

## Expected behavior
A number field should take a number and not a string, just like html fields do. Not only is that logical but also serves as partial input validation (as in I know I will get a number from that field). It was possible to work with numbers before not sure what happened and why this change was needed.

## Steps to reproduce the problem

1. Got to https://polaris.shopify.com/components/forms/text-field#navigation, select number field
2. Open in sandbox 
1. Rplace "1" by 1

## Specifications

- Are you using the React components? (Y/N):y
- Polaris version number: 4.13.1
- Browser: Chrome

```bash

```

**Comment by kaelig** [comment] 2020-02-18 23:43
Hey @AKarmanov – this issue looks like a duplicate of https://github.com/Shopify/polaris-react/issues/2749, was there anything more we could help with?

**Comment by AKarmanov** [comment] 2020-02-19 12:54
Hey, I didn't see my previous issue was closed, I thought it didn't post or something. Anyways ... I understand all the limitations with event returning always a string etc. as indicated in one of the comments to the other issue but since you guys are wrapping <input/> element and effectively overriding onChange functionality can't you parseInt (I'm aware that a number is not always an int, but that's a whole different issue) the event value so that it properly returns a number as one would expect?  Especially given that you do override it  and return value and id (unlike say material-ui-react, which simply passes down original event)?

I just find it mind boggling that I'm sitting here in 2020, working with all this high end, cutting edge tech and I still have to parse my own int coming from a number input!

If you could comment on this it would be great. I understand that changes probably won't happen in the near future so feel free to close the issue. Thanks!

**Comment by kaelig** [comment] 2020-02-20 00:00
Hey Alex – I understand your use-case, however it would be a departure from how native HTML/JS work in browsers (where the type of the value for a number input is `string`).

You can try it for yourself with a native input:

```html
<input type="number" onChange="alert(typeof this.value)" value="1" />
```

Codepen: https://codepen.io/kaelig/pen/jOPMVgx?editors=1011

![Screen Shot 2020-02-19 at 3 55 49 PM](https://user-images.githubusercontent.com/85783/74887667-65392180-5330-11ea-9293-534210b9906e.png)

Whenever possible, Polaris React tries to be consistent with native controls, so that its API is easier to learn and to maintain.

I'll close this duplicate issue, thank you for your understanding!

**Closed by kaelig** 2020-02-20 00:00 UTC
