### ISSUE TITLE
Shopify navigation page reload with react router

### ISSUE THREAD

**Issue by solutionwin2020** [Shopify/polaris-react#3092] opened 2020-07-01 08:26 UTC
Hi i actually working on react and shopify polaris but i am unable to make navigation or routes. the routes which i make is load the page can anyone tell how to make routes with shopify polaris navigations so that the page not reload and component load on page. Here is code.
`<Navigation location="/">
  <Navigation.Section
    items={[
      {
        url: 'settings',
        label: 'Home',
        icon: HomeMajorMonotone,
      },
      {
        url: '/filter',
        label: 'Orders',
        icon: OrdersMajorTwotone,
        badge: '15',
      },
      {
        url: '/search',
        label: 'Products',
        icon: ProductsMajorTwotone,
      },
    ]}
  />
</Navigation>`

`<Router>
        <Switch>
          <Route exact path="/">
            <HomePage value={<DashboardPage />} />
          </Route>
          <Route exact path="/settings">
            <HomePage value={<SettingPage />} />
          </Route>
          <Route exact path="/filter">
            <HomePage value={<FilterTables />} />
          </Route>
          <Route exact path="/installation">
            <HomePage value={<DashboardPage />} />
          </Route>
          <Route exact path="/search">
            <HomePage value={<SearchPage />} />
          </Route>
          <div className="product_layout">
          <Route exact path="/product">
            <HomePage value={<ProductLayout />} />
          </Route>
          </div>
        </Switch>
        </Router>`

**Comment by camelmasa** [comment] 2020-07-01 21:40
Hi, 

We are using React + React Router + Polaris. Also, we are using [shopify-app-history](https://github.com/huckleberry-inc/shopify-app-history).
It's React Hook for Shopify App.

I hope that helps.

**Comment by BPScott** [comment] 2020-07-02 01:14
Duplicate of #3088. Please see my response in that issue.

**Closed by BPScott** 2020-07-02 01:14 UTC
