### ISSUE TITLE
Tabs defaulting to mobile collapse on Chrome

### ISSUE THREAD

**Issue by sniepoort** [Shopify/polaris-react#169] opened 2017-08-17 12:35 UTC
# Issue summary

On Chrome, tabs are defaulting to the mobile collapsed view, instead of a normal desktop view, where all tabs are visible. 

On any window resize event, the tabs expand like they should.

## Expected behavior

Tabs should be expanded when in a desktop window.

![screen shot 2017-08-17 at 14 28 37](https://user-images.githubusercontent.com/10141234/29412287-60cab244-8358-11e7-98fa-52eff101edda.png)

## Actual behavior

The tabs are shown collapsed, even in a desktop window.
When a resize event occurs, the tabs expand like expected.

![screen shot 2017-08-17 at 14 28 06](https://user-images.githubusercontent.com/10141234/29412279-565ff99a-8358-11e7-8aee-c71204ea6baa.png)

## Steps to Reproduce the Problem

1. Add markup like so:
```javascript
<Page
  title="Export activities"
>
  <Layout sectioned>
    <Tabs
      selected={0}
      tabs={[
        {
          id: 'tabs-1',
          title: 'Admin',
          panelID: 'admin',
        },
        {
          id: 'tabs-2',
          title: 'Teachers',
          panelID: 'teachers',
        },
        {
          id: 'tabs-3',
          title: 'Students',
          panelID: 'students',
        },
      ]}
      onSelect={this.handleTabIndex}
    >
    </Tabs>

  </Layout>
</Page>
```

2. View in Chrome browser, on a desktop screen.

## Specifications

- Polaris version: 1.3.1
- React version: 15.6.1
- Browser: Chrome
- Device: Computer
- Operating System: OSX

**Comment by dfmcphee** [comment] 2017-10-06 20:50
Hey @sniepoort. Thanks for submitting an issue. I am unable to reproduce this using the example you gave. Can you verify this is still an issue in 1.7.0?

**Comment by Anveio** [comment] 2017-10-08 06:26
I can corroborate that this is still happening for me in 1.7.0 in Chrome 61 and Firefox 56. Can inconsistently reproduce it in Chrome but am able to reproduce it 100% of the time in Firefox. Seems to only happen when pulling the stylesheet from the CDN and never when importing styles from the package.

**Comment by ry5n** [comment] 2018-03-29 02:11
Just trying to reproduce this again. Are you using the React component, or the markup and styles?

**Comment by ry5n** [comment] 2018-06-02 18:48
Just tried this again with Polaris 2.1.1, and I can’t reproduce. Test case: https://codesandbox.io/s/18y988q8vl

Please let us know if you still have this issue.

**Comment by cgenevier** [comment] 2018-08-01 15:44
@ry5n I'm having this same problem on 2.5.0:

<img width="1408" alt="screen shot 2018-08-01 at 9 40 25 am" src="https://user-images.githubusercontent.com/1074752/43532290-f782dcd8-956e-11e8-8a7a-649c0c1c6d93.png">

Interestingly, it appears to happen when the page first loads - if I resize the browser window, the tabs go back to the correct non-mobile view.

**Comment by ry5n** [comment] 2018-08-01 23:48
I updated [the test case](https://codesandbox.io/s/18y988q8vl) to 2.5.0 and I don’t immediately see the issue. I wonder if this is a development-only problem… 🤔

Can you do me a favor? Try temporarily changing this line of code:

https://github.com/Shopify/polaris/blob/master/src/components/Tabs/TabMeasurer.tsx#L37

The link above is to the source code, but you‘ll be changing it in the package from npm: `node_modules/`@shopify/polaris/index.js`. The equivalent line should be somewhere around line 10890.

Change the second argument in `setTimeout(this.handleMeasurement, 0);` to maybe `100`. Add a `console.log` to make sure the change is being picked up and see if the issue is still present?

**Comment by cgenevier** [comment] 2018-08-02 17:57
@ry5n 

More information: It looks like for me, the variable `process.env.NODE_ENV` is undefined so it's not even running that setTimeout. That said, when I pulled the setTimeout out of the if statement, it totally solved the problem, even when set to 0.

**Comment by ry5n** [comment] 2018-08-02 20:18
Hmmmm that’s a good lead at least. How are you bringing in the Polaris styles? And the javascript? (Are you using a module bundler like Webpack?)

**Comment by AndrewMusgrave** [comment] 2018-08-02 21:16
> More information: It looks like for me, the variable process.env.NODE_ENV is undefined so it's not even running that setTimeout. That said, when I pulled the setTimeout out of the if statement, it totally solved the problem, even when set to 0.

Javascript is a single threaded. `setTimeout` will place the function on the end of the message queue which is why a `setTimeout(fn, 0)` forces `fn` to run after all the other code has executed :)

**Comment by adolfoyanes** [comment] 2018-09-05 22:55
Any news on this? I am having the same issue. It load correctly if you enter directly to www.marketful.mx/fulfillment/soporte but you get the bug when you enter www.marketful.mx/shopify and then click on Soporte (down to the left).

**Comment by ry5n** [comment] 2018-10-25 23:13
@AndrewMusgrave can you confirm whether this would be an issue in production, or is it confined to development?

**Comment by tmlayton** [comment] 2018-11-16 23:15
Hey folks, I’m going to close this issue for now. It seems infrequent enough that I’m hesitant to ship a fix like sniffing out if the styles have loaded for a node before measuring which could negatively impact the performance. If someone can create a reduced test case that isolates the issue, we can reopen and look at fixing.

In the meantime, a simple workaround is to manually trigger a window resize event (`window.dispatchEvent(new Event('resize'))`) after the tabs are loaded.

**Closed by tmlayton** 2018-11-16 23:15 UTC
Labels: Bug

**Comment by mrtnpro** [comment] 2019-03-21 11:24
We're experiencing the same issue. As @tmlayton suggested the following line saved us:
```
componentDidMount() {
    setTimeout(() => window.dispatchEvent(new Event('resize')), 500);
  }
```

It doesn't look nice, especially the jumping and re-rendering of the Tabs but it does the job for now.

**Comment by Popesites** [comment] 2019-08-04 18:17
Hello! I am having this issue now as well. It only occurs when my application is running in production mode.

**Comment by AndrewMusgrave** [comment] 2019-08-07 17:16
Hi @Popesites , would you be able to supply a minimal reproduction?
