### ISSUE TITLE
[Autocomplete][v1] UI Performance Issues w. Auto-Complete as Multi-Select

### ISSUE THREAD

**Issue by TheEnzoMar** [Shopify/polaris-react#644] opened 2018-11-19 16:36 UTC
## Issue summary
In an attempt to use the `AutoComplete` component as a way to provide a multi-select functionality for a large dataset (a country list), we encountered significant UI performance issues; which include slow to respond UI and janky animations.

I'm not sure if this is an intended use for the AutoComplete component, but it was suggested as a solution in the `#web-foundation-apps` channel. 

See https://codesandbox.io/s/1yrqk88r3q for a demo of the issue

## Expected behavior
I would expect the AutoComplete component UI to be performant

## Actual behavior
- Slow to respond UI
- Janky animations
- Not ideal user experience

## Specifications
- Are you using the React components? YES:
- Polaris version number: 3.0
- Browser: Chrome v.70.0.3538.102
- Device: MacBook Pro
- Operating System: macOS Mojave v10.14

**Comment by solonaarmstrong** [comment] 2018-11-19 16:46
Thank you @TheEnzoMar, I will have a look.

**Comment by chloerice** [comment] 2018-11-19 18:22
Hey @TheEnzoMar, thanks for raising this issue! Do you happen to have a gif or the issues you're seeing, or can you be more specific about how to reproduce? In playing with the CodeSandbox you linked, I'm not experiencing issues 🤔.

**Comment by solonaarmstrong** [comment] 2018-11-19 18:31
@chloerice  I can see some lag when typing/deleting and the component is searching for results. The scrolling is a bit janky, too.

**Comment by TheEnzoMar** [comment] 2018-11-19 19:37
Hey @chloerice, I've attached a gif to highlight the issues. Cheers! 
![](https://im.ezgif.com/tmp/ezgif-1-f0f11c55e0ed.gif)

cc: @solonaarmstrong

**Comment by chloerice** [comment] 2018-11-19 20:14
Thanks @TheEnzoMar!

**Comment by darrenhebner** [comment] 2018-11-28 16:02
Just noticed this ticket, but we are experiencing the same issue in the marketing section. We decided to ship anyways since even with the performance issue, the new typeahead was still better than what we were using before.

We did notice that the performance was significantly better in production.

**Comment by dleroux** [comment] 2019-07-18 11:31
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Closed** 2020-01-21 12:33 UTC
Labels: Icebox, ⚗️ Development, 🌟 Autocomplete, 🎨 Design
