### ISSUE TITLE
[TrapFocus] causes infinite loop when used in a Dialog

### ISSUE THREAD

**Issue by darrenhebner** [Shopify/polaris-react#2641] opened 2020-01-21 19:20 UTC
## Issue summary
The `TrapFocus` component appears to be creating an infinite loop. If you look at the stacktrace below, you can see that `Dialog` triggers `focusFirstFocusableNode` which triggers a `focusin` event. This event triggers `handleFocusIn` which calls `focusFirstFocusableNode`. The loop keeps going.

This ends up locking the main thread for a significant time.

<img width="852" alt="Screen Shot 2020-01-21 at 1 55 52 PM" src="https://user-images.githubusercontent.com/4441303/72834431-d369c600-3c56-11ea-85d4-62433242206f.png">

## Expected behavior
After the initial focus, the loop should stop.

## Steps to reproduce the problem
This doesn't appear to be happening with all modals. I haven't been able to identify what scenario causes this bug.

cc @devonpmack @AndrewMusgrave

**Comment by LauraAubin** [comment] 2020-01-21 19:40
👀@lauraaubin @dleroux

**Comment by dleroux** [comment] 2020-01-22 14:18
I think the issue is because TrapFocus is actually working now and the component in question is rendering 2 modals at the same time. There is a PagedModal component and Modal rendering at the same time. So when the PageModal plays out, the other loads and trap focus gets confused.  Still investing to confirm.

**Comment by dleroux** [comment] 2020-01-22 15:10
Pretty sure I fixed the issue in web but we should probably find a way to prevent this from happening.

**Comment by darrenhebner** [comment] 2020-01-22 18:12
Good find @dleroux! Thanks for looking in to this.

**Comment by devonpmack** [comment] 2020-01-27 20:00
@dleroux Can we only render a `TrapFocus` when open is true?

**Comment by dleroux** [comment] 2020-01-27 20:25
Currently, that is the case. TrapFocus only gets rendered when open is true. The current implementation actually has a moment where 2 modals have the open prop because of the animation. We will find a solution to prevent this is Polaris, this particular implementation should be fixed as well. Maybe the solution is to include the column reordering modal as be part of the paged modal, I'm not sure.

**Comment by devonpmack** [comment] 2020-01-27 20:31
Oh I see thanks for clarifying. It's not currently blocker for us as we can easily work around it.

**Closed** 2020-02-05 16:39 UTC
Labels: 🐛Bug
