### ISSUE TITLE
Autocomplete misbehaves with asynchronous options

### ISSUE THREAD

**Issue by mattrothenberg** [Shopify/polaris-react#3643] opened 2020-11-18 13:10 UTC
## Issue summary
When setting `options` after an asynchronous operation, the `Autocomplete` component doesn't render the interactive list of options until a user presses down on their keyboard.

This can be reproduced on the **Autocomplete with loading** demo on https://polaris.shopify.com/components/forms/autocomplete.

**Demo**
![Kapture 2020-11-18 at 8 09 20](https://user-images.githubusercontent.com/5148596/99534450-6a85d400-2975-11eb-8a86-ebb74e81c874.gif)

## Expected behavior
The option menu should be visible after the `options` prop changes values following an asynchronous operation.

## Actual behavior
The option menu remains hidden after the `options` prop changes values following an asynchronous operation.

## Steps to reproduce the problem

1. Type "r" in the autocomplete box
2. Observe that the option list is hidden
3. Press the down button on your keyboard
4. Observe that the option list is visible

**Comment by roark** [comment] 2020-12-21 03:04
I'm experiencing this as well. The AutoComplete will not redisplay the updated options unless an explicit down arrow key is pressed.

**Comment by jonpulsifer** [comment] 2020-12-23 14:58
Duplicate of https://github.com/Shopify/polaris-react/issues/3048

**Closed by jonpulsifer** 2020-12-23 14:58 UTC
Labels: 🐛Bug
