### ISSUE TITLE
DropZone.FileUpload: Typescript error

### ISSUE THREAD

**Issue by chhornponleu** [Shopify/polaris-react#1217] opened 2019-03-16 23:51 UTC
# Issue summary
I have just upgraded the project to type script. Running is ok, but error when building for production.

<img width="906" alt="Screen Shot 2019-03-16 at 12 00 29 PM" src="https://user-images.githubusercontent.com/14964945/54476865-76ca9d00-4834-11e9-9d5c-3c181c686160.png">

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
  },
  "include": [
    "src",
    "types/**/*"
  ]
}
```

```
"typescript": "^3.3.3333"
```

**Comment by BPScott** [comment] 2019-03-18 18:30
Hi @chhornponleu,

This is the same problem as #711 where context typing is broken in TypeScript > v3.2.0. The root cause of this issue is  due to a bug in react-compose (see https://github.com/Shopify/quilt/issues/489).

Until react-compose gets updated, you can downgrade Typescript to v3.1.x and things should compile successfully.

**Comment by BPScott** [comment] 2019-03-18 18:31
Closing this as it is a duplicate of #711.

**Closed by BPScott** 2019-03-18 18:31 UTC
Labels: Bug
