### ISSUE TITLE
[Collapsible] Clips overflow

### ISSUE THREAD

**Issue by trungdunghbvn** [Shopify/polaris-react#408] opened 2018-08-27 04:28 UTC
https://prnt.sc/kn8p1v

**Comment by markiiikram** [comment] 2018-08-27 16:36
Thanks for reporting the issue @trungdunghbvn. I opened an issue to track internally and we will post back here when it is resolved.

**Comment by ry5n** [comment] 2018-10-25 23:08
I can verify this based on the attached screenshot. The cause is the collapsible component has `overflow: hidden`.

If we remove the overflow declaration, it causes some issues with content overlapping during the open/close transition. The following gif shows first with then without the overflow.

![screen capture on 2018-10-25 at 16-04-32](https://user-images.githubusercontent.com/804014/47535327-e6cd8c00-d86f-11e8-9734-762514c2e3d9.gif)

We could look into applying the overflow only during the transition.

**Comment by danrosenthal** [comment] 2019-02-13 12:53
This should now be closed as of https://github.com/Shopify/polaris-react/pull/951

**Closed by danrosenthal** 2019-02-13 12:53 UTC
Labels: Bug
