### ISSUE TITLE
Banner with long sentences inside Stack breaks margin

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/polaris-react#1068] opened 2019-02-20 18:59 UTC
# Issue summary

Experienced some margin issues when you use a somewhat long `Banner` sentence contained in a Stack. I was able to reproduce this in a Modal, not sure if it happens using other parent components. 

https://codesandbox.io/s/2vp7zop13j:

<img width="636" alt="screen shot 2019-02-20 at 1 55 22 pm" src="https://user-images.githubusercontent.com/6130700/53116728-551d1500-3517-11e9-8e9a-2d7d47087ab0.png">

@dleroux  suggested using a `TextContainer` instead of a `Stack`, which fixed the issue - [code sandbox](https://codesandbox.io/s/pwml927oyj). Not sure if the Banner inside a Stack issue is a real bug or misuse of component nesting.

**Comment by AndrewMusgrave** [comment] 2019-02-20 19:13
Is this possibly related too https://github.com/Shopify/polaris-react/issues/947?

**Comment by dleroux** [comment] 2019-02-20 19:20
Quite possibly another Chrome 72 flexbox issue.

**Comment by ry5n** [comment] 2019-02-21 02:00
Closing as duplicate of #947, related to changes in Chrome 72. Further discussion in PR #1024

**Closed by ry5n** 2019-02-21 02:00 UTC
