### ISSUE TITLE
Page Icon does not show on the page when embedded.

### ISSUE THREAD

**Issue by rhmtech** [Shopify/polaris-react#1690] opened 2019-06-16 13:50 UTC
## Issue summary

When testing `icon` outside of embedded it seems it is working.  Not able to render it when app is embedded.

## Expected behavior

Snip of the code
https://codesandbox.io/embed/adoring-carson-hsiwy

## Actual behavior
The icon does not render. 

![image](https://user-images.githubusercontent.com/44618465/59565017-e579eb00-901b-11e9-83ab-31564aa3739d.png)

## Steps to reproduce the problem
1. Embed app

## Specifications

```bash
npx: installed 1 in 1.922s

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 72.14 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - ~/zoocommerce/chameleon/node_modules/.bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Firefox: 67.0.2
    Safari: 12.1
  npmPackages:
    @shopify/polaris: ^3.17.0 => 3.17.0
    react: ^16.8.6 => 16.8.6
    react-dom: ^16.8.6 => 16.8.6
```

**Comment by rhmtech** [comment] 2019-06-16 17:17
@chloerice @BPScott  thanks guys for initial help on this but I was not able to make it is working under embedded. I exhausted my knowledge and no idea where else to check.  :(

**Comment by danrosenthal** [comment] 2019-06-17 19:23
@rhmtech this is by design. The `Page` `Header` delegates its rendering to the Shopify App Bridge when in an embedded context (if an APIKey is passed to the `AppProvider` component at the top of your component tree). The App Icon is now configured using the Partner Dashboard.

See this code: https://github.com/Shopify/polaris-react/blob/master/src/components/Page/Page.tsx#L95

And these docs: https://polaris.shopify.com/components/structure/page#section-use-in-an-embedded-application-deprecated-

Closing as this is functioning as designed.

**Closed by danrosenthal** 2019-06-17 19:23 UTC

**Comment by rhmtech** [comment] 2019-06-17 21:07
thank you @danrosenthal  It would be nice to update docs too. It is a bit confusing!
