### ISSUE TITLE
Failing tests are passing

### ISSUE THREAD

**Issue by samjrdn** [Shopify/polaris-react#1128] opened 2019-03-06 16:10 UTC
# Issue summary

There are a number of tests, specifically in [`ComboBox.test.tsx`](https://github.com/Shopify/polaris-react/blob/2a56c498d462ab990ebab5f4d1d94ba4452ef4ff/src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx#L431) and perhaps elsewhere, that are passing because the assertions are not called.

The affected code has this pattern:
```
async () => {
  comboBox.find(TextField).simulate('click');
  listenerMap.keyup({keyCode: Key.DownArrow});
  await expect(comboBox.state('selectedIndex')).toBe(0);
};
```
which declares a function that never gets executed.

## Expected behavior

The code wrapped inside the async arrow functions should be executed.

## Actual behavior

The code inside the async arrow functions is never executed because the async arrow function is declared but never called.

## Steps to reproduce the problem

1. Add a `throw Error()` inside the async arrow function
1. Run the test and observe that it still passes

## Possible solution

Modify tests with the following pattern:

```
it('test description', () => {
  ...
  async () => {
    await ...
  };
});
```

to be

```
it('test description', async () => {
  ...
  await ...
});
```

It is also a good idea to verify the number of assertions the test will call using [`expect.assertions(number)`](https://jest-bot.github.io/jest/docs/expect.html#expectassertionsnumber).

**Comment by chloerice** [comment] 2019-03-06 17:37
Crossing linking to duplicate issue https://github.com/Shopify/polaris-react/issues/1124

**Comment by danrosenthal** [comment] 2019-03-06 18:00
Let's close this as a duplicate of https://github.com/Shopify/polaris-react/issues/1124

**Closed by danrosenthal** 2019-03-06 18:00 UTC
