### ISSUE TITLE
AppBridge silently fails if the "App URL" does not match postMessage origin

### ISSUE THREAD

**Issue by marguskoiduste** [Shopify/polaris-react#1332] opened 2019-04-17 16:56 UTC
# Issue summary

AppBridge (Embedded app) silently ignores all messages if the postMessage origin does not match the "App URL" set on the partner dashboard. This is very hard to debug.

## Expected behavior

Log an error or warning in the browser console.

## Actual behavior

I had "App URL" with "http" set on my partner dashboard. The app internally redirected to "https" URL. None of the AppBridge features (Redirect, Toast, Loading) worked and no error was logged.

Also please see similar issue: https://community.shopify.com/c/Shopify-APIs-SDKs/Using-the-new-shopify-app-bridge-with-shopify-polaris-react/td-p/494939/page/2

## Steps to reproduce the problem

1. Set "App URL" to "http"
2. On server side redirect to "https"
3. Try using any of the AppBridge features

## Reduced test case

N/A

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.12.0
- Browser: N/A
- Device: N/A
- Operating System: N/A

**Comment by dpersing** [comment] 2019-04-17 17:48
Hi @marguskoiduste! This is an issue with App Bridge, so the community thread you linked to (https://community.shopify.com/c/Shopify-APIs-SDKs/Using-the-new-shopify-app-bridge-with-shopify-polaris-react/td-p/494939/page/2) is the best place to keep an eye out for updates. The App Bridge team knows this is an issue and is actively tracking It.

I'll close this issue here for now, since the problem is happening outside of Polaris.

**Closed by dpersing** 2019-04-17 17:48 UTC
Labels: App Bridge, Bug
