### ISSUE TITLE
ResourceList.Item expects `polaris` and `context` props

### ISSUE THREAD

**Issue by mikeyhew** [Shopify/polaris-react#1238] opened 2019-03-21 21:47 UTC
# Issue summary

Somehow typescript thinks that `ResourceList.Item` requires the `polaris` and `context` props, when in fact it does not.

## Expected behavior

This code should compile:

```tsx
import * as React from "react";
import { render } from "react-dom";
import {
  AppProvider,
  Card,
  Layout,
  Page,
  ResourceList
} from "@shopify/polaris";
import "@shopify/polaris/styles.css";

const Playground = () => (
  <AppProvider>
    <Page title="Playground">
      <Layout sectioned>
        <Card sectioned>
          <ResourceList
            items={[1, 2, 3]}
            renderItem={(item: number) => (
              <ResourceList.Item url="some-url" id={item.toString()}>
                <p>Item {item}</p>
              </ResourceList.Item>
            )}
          />
        </Card>
      </Layout>
    </Page>
  </AppProvider>
);

render(<Playground />, document.getElementById("root"));
```

## Actual behavior

Typescript error message:

```
Type '{ children: Element; id: string; url: string; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Item> & Readonly<PropsWithUrl & WithAppProviderProps & WithContextTypes<ResourceListContext>> & Readonly<{ children?: ReactNode; }>) | (IntrinsicAttributes & ... 2 more ... & Readonly<...>)'.
  Type '{ children: Element; id: string; url: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Item> & Readonly<PropsWithClick & WithAppProviderProps & WithContextTypes<ResourceListContext>> & Readonly<{ children?: ReactNode; }>'.
    Type '{ children: Element; id: string; url: string; }' is missing the following properties from type 'Readonly<PropsWithClick & WithAppProviderProps & WithContextTypes<ResourceListContext>>': onClick, polaris, context
```

## Steps to reproduce the problem

1. `git clone https://github.com/mikeyhew/polaris-resource-list-item-bug-example`
1. cd polaris-resource-list-item-bug-example
1.`yarn && yarn tsc`

## Reduced test case

Here is a github repo with a reduced test case. I tried to use CodeSandbox, but it apparently doesn't do any type-checking.

https://github.com/mikeyhew/polaris-resource-list-item-bug-example/blob/master/src/playground.tsx

## Specifications

- Are you using the React components? Yes
- Polaris version number: 3.11.0
- Browser: N/A
- Device: Macbook Air
- Operating System: macOS 10.13

**Comment by BPScott** [comment] 2019-03-21 22:53
Hi @mikeyhew,

This is the same problem as #711 where context typing is broken in TypeScript > v3.2.0. The root cause of this issue is due to a bug in react-compose (see Shopify/quilt#489).

Until react-compose gets updated, you can downgrade Typescript to v3.1.x and things should compile successfully.

**Comment by BPScott** [comment] 2019-03-21 22:53
Closing this as it is a duplicate

**Closed by BPScott** 2019-03-21 22:53 UTC
Labels: Bug

**Comment by mikeyhew** [comment] 2019-03-22 00:03
Thanks!
