### ISSUE TITLE
Submit button heavily weighted on bottom

### ISSUE THREAD

**Issue by iSamMitchell** [Shopify/polaris-react#2580] opened 2019-12-24 16:49 UTC
## Issue summary
The button to submit for a free copy of anything from the partners blog is heavily weighted at the bottom of itself, conflicting with the look and feel of other Polaris buttons in comparison. Not sure if issue resides on Polaris or Brochure, but Polaris is open 🤷🏻‍♂️
### Issue Examples
![image](https://user-images.githubusercontent.com/17798017/71420062-12e5c800-2641-11ea-8bbb-f839519c5b77.png)
[Example 1 found on this page](https://www.shopify.ca/partners/blog/100022086-how-to-write-a-design-brief-to-keep-your-web-design-projects-on-track)
![image](https://user-images.githubusercontent.com/17798017/71420196-eed6b680-2641-11ea-899c-d810b0e3c3dc.png)
[Example 2 found on this page](shopify.ca/partners/blog/87782278-how-to-write-a-web-design-case-study-that-lands-new-clients?_pos=1&_sid=463876ea1&_ss=r)
### Normal example?
<img width="346" alt="Screen Shot 2019-12-24 at 11 31 51 AM" src="https://user-images.githubusercontent.com/17798017/71420245-2fcecb00-2642-11ea-94a7-d73028499c71.png">

The amount of padding on top of the aforementioned problematic button seems larger than that of other buttons used throughout the partners blog. This is occurring multiple times on the blog, in the same kind of container (submission for free copy of something). 

## Expected behavior
Look and feel matching other buttons with similar use and padding.

## Actual behavior
See above for potential normal example

## Steps to reproduce the problem

Hit one of the above example links to see the issue.

## Reduced test case
- Browser: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Device: MacBook Pro (Retina, 13-inch, Early 2015)
- Operating System: macOS Mojave Version 10.14

cc @LauraAubin @mateus

**Comment by kaelig** [comment] 2020-06-22 22:01
I couldn't reproduce this issue so I will close it.

**Closed by kaelig** 2020-06-22 22:01 UTC
Labels: Icebox
