### ISSUE TITLE
Add viewport meta tag to Storybook

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#896] opened 2019-01-17 20:03 UTC
Currently even when viewing the isolated component (http://localhost:6006/iframe.html?selectedKind=Playground&selectedStory=Playground) components can only be viewed on mobile in desktop size because of the absence of a viewport meta tag.

[Potential fix here](https://github.com/Shopify/polaris-react/pull/852/commits/7d41ec099ea44f88994bef7ba8a7d4fb9ff6ad88)

![screen shot 2019-01-17 at 3 03 20 pm](https://user-images.githubusercontent.com/4029894/51345460-0c31f680-1a69-11e9-9e85-1fd512e5e27a.png)

**Comment by ry5n** [comment] 2019-02-05 23:31
This prevents us from manually testing component changes in mobile browsers—pretty important. Just checked master; [the potential fix linked to above](https://github.com/Shopify/polaris-react/pull/852/commits/7d41ec099ea44f88994bef7ba8a7d4fb9ff6ad88) is merged, but the issue is still there.

**Comment by kvendrik** [comment] 2019-02-06 16:00
@ry5n https://github.com/Shopify/polaris-react/pull/852/commits/7d41ec099ea44f88994bef7ba8a7d4fb9ff6ad88 was never merged as it was out-of-scope for the PR, it was removed in https://github.com/Shopify/polaris-react/pull/852/commits/39d74ddc3244d708a31209cc3869a8d678c54739. 🙂

**Comment by ry5n** [comment] 2019-02-06 16:07
🙋‍♂️ If that changeset is all that’s needed I’m happy to open it as a new PR

**Comment by kvendrik** [comment] 2019-02-06 16:30
@ry5n seems to be the case but wanted to address it separately at some point as I don't know if there are edge cases where it could potentially mess up the testing env. Feel free to open a PR 🙂

**Comment by kvendrik** [comment] 2019-02-11 22:26
Note: the fix seems to only work when on `http://localhost:6006/iframe.html?selectedKind=Playground&selectedStory=Playground` and not within the StoryBook UI. cc @ry5n

**Closed** 2019-02-22 20:42 UTC
