### ISSUE TITLE
[New DL] Missing background in stepper field

### ISSUE THREAD

**Issue by cherrychau** [Shopify/polaris-react#3269] opened 2020-09-17 21:01 UTC
**Actual** The up and down icons in the stepper are missing backgrounds. To recreate this, create a shipping label for an order, click "Add package" and it will open up this modal.
<img width="260" alt="Screen Shot 2020-09-17 at 4 56 34 PM" src="https://user-images.githubusercontent.com/51451924/93527602-1aec4300-f907-11ea-9438-9dfdfc57117c.png">

**Expected** This is the version in Figma
<img width="421" alt="Screen Shot 2020-09-17 at 4 59 50 PM" src="https://user-images.githubusercontent.com/51451924/93527752-5555e000-f907-11ea-8129-4e0aba615ee1.png">

-------
**Update:**

Other areas where the missing background in the field can be found include the **Create shipping label** page
<img width="692" alt="Screen Shot 2020-09-30 at 3 08 48 PM" src="https://user-images.githubusercontent.com/51451924/94728932-fa70af80-032e-11eb-9b10-c3355955a3f9.png">

**Comment by AndrewMusgrave** [comment] 2020-09-18 15:09
👋  @cherrychau I took a look in the code and it doesn't look like you're using `type=number` on the text fields. So this is something you'll have to fix on your side. I'm going to close this, for now, feel free to reopen it if the problem persists!

**Comment by lucasfrosty** [comment] 2020-09-25 15:12
Reopening this. We are using type number on the version in shipping labels. You probably looked at the version that is on Shipping Settings (don't ask me why there's 2 versions cause i honestly don't know, i plan to unify them at some point).

**Comment by alex-page** [comment] 2020-09-25 15:28
Should this be moved from `polaris-react` because the issue doesn't exist in this repo?

**Comment by lucasfrosty** [comment] 2020-09-25 15:36
Depends on what it's causing it, it may be a bug that for now only we found and report, but maybe some other places are facing the same issue as well. I'll do some investigation to try to find the cause and i'll come back here to see where we keep the conversation.

**Comment by alex-page** [comment] 2020-09-25 15:41
Thanks! From the number field has a minor bug in Polaris but looks different to your implementation:
http://polaris-react.herokuapp.com/iframe.html?id=all-components-text-field--number-field&contexts=New%20Design%20Language%3DEnabled%20-%20Light%20Mode

**Comment by lucasfrosty** [comment] 2020-09-25 15:43
Okay, i think i found the problem: apparently the version in figma is different from the version in development.
The question is: which one is correct? I assume is the dev one. If that's the case, i think we're good and we just need to update figma with the new design.

**Comment by alex-page** [comment] 2020-09-25 17:04
The Figma design is correct, our number field has a regression. I think your number field is forked though because when this issue was originally logged the number field was working differently.

**Comment by alex-page** [comment] 2020-10-26 21:10
This should be resolved as we updated the stepper background color. Let me know if this is still an issue.

**Closed by alex-page** 2020-10-26 21:10 UTC
Labels: 🐛Bug
