### ISSUE TITLE
[DataTable] 1st column blank on iOS Safari narrow screens

### ISSUE THREAD

**Issue by andrewlo** [Shopify/polaris-react#489] opened 2018-10-29 17:40 UTC
# Issue summary
On my iPhone 6S with iOS 12 in portrait mode, on Safari or inside Shopify mobile app, Data Table's 1st row appears blank:

On Polaris Styleguide:
![img_470b021b6394-1](https://user-images.githubusercontent.com/1470768/46585253-87cce200-ca3c-11e8-924a-ca5c148e5a40.jpeg)

In an embedded app:
![img_1611](https://user-images.githubusercontent.com/1470768/46585254-87cce200-ca3c-11e8-8103-d54c1227f244.PNG)

It doesn't happen in landscape:
![img_1612](https://user-images.githubusercontent.com/1470768/46585265-bf3b8e80-ca3c-11e8-95f3-ccab96a0ed1d.PNG)

## Expected behavior

Left column not blank on iOS mobile

## Actual behavior

Left column is blank on iOS mobile

## Steps to reproduce the problem

Issue is visible on Polaris style guide on iOS mobile Safari in portrait mode

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:
- Browser: Safari
- Device: iPhone
- Operating System: iOS 12

**Comment by BPScott** [comment] 2018-10-29 18:56
From @solonaarmstrong on the original private issue:

> I had a quick look and I think this might be related to using position: absolute in iOS/mobile. I am a bit stretched thin, so if anyone wants to pick this up, please do.
> 
> https://stackoverflow.com/questions/15933498/issues-with-absolute-positioning-of-div-in-mobile-browser
> https://blog.idrsolutions.com/2013/05/ios-and-html5-gotcha-with-absolute-positioning/

**Comment by sergey-alekseev** [comment] 2019-04-12 08:11
@BPScott thanks for the details. Any idea when this is going to be fixed? It's currently on the last issues page, so there is a chance everyone forgets about this.

**Comment by dleroux** [comment] 2019-04-12 11:46
I spent some time the other day looking at this but didn't get to a solution. It is an issue with the first column being absolute positioned and not appearing outside the `overflow-x: auto` div. Tried playing around with the [position: relative](http://front-back.com/how-to-make-absolute-positioned-elements-overlap-their-overflow-hidden-parent) but that didn't work. Unfortunately busy on another project at the moment so hopefully someone else can have a look.

**Comment by sergey-alekseev** [comment] 2019-04-12 11:47
@dleroux thanks for the info.

**Comment by chloerice** [comment] 2019-05-07 16:50
After looking into this, the problem seems to be that the absolute positioning of the first column in order to fix it in place doesn't work properly in Safari. Nothing I've tried so far CSS-wise has been able to quell the blank rendering of the cells. My guess is that this is a regression of the removal of the presentational column in https://github.com/Shopify/polaris-react-deprecated/pull/1723. 

I'm focused on https://github.com/Shopify/web/issues/13367 right now since there seems to be so much urgency around it, but will checkout master in a commit prior to #1723 shipping to try to pinpoint if the issue in Safari came with that PR once the other issue mentioned is fixed.

**Comment by ruairiphackett** [comment] 2019-05-08 10:42
Had a look into this and couldn't find any simple solution either. [This was the only example](https://codepen.io/paulobrien/pen/gWoVzN) that I saw that works on iOS devices with the width of the table exceeding the viewport width.

Unfortunately it involves having a duplicate of the table in the DOM and using one version to display the fixed column and the other to display the scrollable columns. I could put together a PR based on it, but I imagine it might not be a desirable way of solving this.

**Comment by ruairiphackett** [comment] 2019-05-08 10:45
Video of codepen above on iPhone 6S Simulator: https://screenshot.click/2019-05-08_11-44-17.mp4

**Comment by chloerice** [comment] 2019-07-12 17:56
Fixed by https://github.com/Shopify/polaris-react/pull/1605

**Closed by chloerice** 2019-07-12 17:56 UTC
Labels: ⚗️ Development, 🐛Bug
