### ISSUE TITLE
Order detail page Timeline detail 

### ISSUE THREAD

**Issue by raghu-c** [Shopify/polaris-react#2914] opened 2020-04-13 07:12 UTC
## Issue summary
Order detail page Timeline detail 

## Actual behavior
Not able to find the components, to develop the same. 

1. We have multiple scenarios to handle the timeline.
2. Need to differentiate the order status alert(in terms of color) 

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by raghu-c** [comment] 2020-04-17 09:26
Timeline reference image 

![orders](https://user-images.githubusercontent.com/59169757/79554409-a4c78400-80bb-11ea-824b-a75b2f4d248c.jpg)

**Comment by 8eecf0d2** [comment] 2020-04-22 08:46
Component status is available here https://polaris.shopify.com/components/component-status

The **Timeline** component is **Not currently planned**, which is unfortunate.

**Comment by raghu-c** [comment] 2020-04-22 09:08
Thanks for the response.

**Comment by chloerice** [comment] 2020-04-22 22:29
Closing as this is a duplicate of #298

**Closed by chloerice** 2020-04-22 22:29 UTC
