### ISSUE TITLE
Gallery view design (4 card with Odd number of images) 

### ISSUE THREAD

**Issue by raghu-c** [Shopify/polaris-react#2829] opened 2020-03-12 07:24 UTC
## Issue summary We are trying to create a gallery view (4 card layout) using Polaris standard card pattern. 5th card occupies full space. How to fix the card width? Any other ideas to explore the expected design.
![photos_123](https://user-images.githubusercontent.com/59169757/76497580-49bdc400-6461-11ea-8f7b-31ba7f1bf0fe.png)

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by BPScott** [comment] 2020-03-12 17:23
Duplicate of #2830

**Closed by BPScott** 2020-03-12 17:23 UTC
