### ISSUE TITLE
[Autocomplete][v1] with connected component - options pop up incorrectly

### ISSUE THREAD

**Issue by mikeyhew** [Shopify/polaris-react#1559] opened 2019-05-23 00:36 UTC
## Issue summary

For an Autocomplete text field with a connected component, the autocomplete options pop up when you click on the connected component.

## Expected behavior

The autocomplete options should only pop up when you click on the text field itself, not on a connected component.

## Actual behavior

The autocomlete options pop up when you click on the connected component:

![Screen Shot 2019-05-22 at 8 23 17 PM](https://user-images.githubusercontent.com/6751033/58217411-bbf5ca00-7cd0-11e9-9932-2fda4785c2c8.png)

## Steps to reproduce the problem

1. Create an `Autocomplete` component with one or more `options` an `Autocomplete.TextField` that has a connected `Select` component.
1. Click on the connnected `Select` component
1. Watch the autocomplete options pop up

## Reduced test case
https://codesandbox.io/s/shopify-polaris-react-typescript-playground-7hq83

## Specifications

- Are you using the React components? Yes
- Polaris version number: 3.15.0
- Browser: Firefox
- Device: Macbook Air
- Operating System: macOS 10.13

**Comment by AndrewMusgrave** [comment] 2019-05-23 22:08
cc/ @chloerice

**Comment by alexieyizhe** [comment] 2019-06-05 21:34
I was playing around with this bug since I was looking to contribute and I found that the root cause of it is that if a connected component of a `textField` registers a click or focus event, the event bubbles up to the `ComboBox` in the `Autocomplete` component which triggers its handlers for that event.

It can be fixed with an `event.stopPropagation()` like so in the `Connected` component:
```js
const leftConnectionMarkup = left ? (
    <Item position={ItemPosition.Left}>
      <span
        onClick={(e) => e.stopPropagation()}
        onFocus={(e) => e.stopPropagation()}
      >
        {left}
      </span>
    </Item>
  ) : null;

  const rightConnectionMarkup = right ? (
    <Item position={ItemPosition.Right}>
      <span
        onClick={(e) => e.stopPropagation()}
        onFocus={(e) => e.stopPropagation()}
      >
        {right}
      </span>
    </Item>
  ) : null;
```
but I'm not sure if it's a good solution since that can possibly cause problems down the line for other components, and it adds an additional span element. I'm also not sure if that's the best place to put it, but my reasoning for it being there is that two connected components should not affect each other.

Another solution I thought of was changing the composition of the elements to something more logical, where the `Connected` component wraps the Autocomplete and the Select as its two children.

I'm new to contributing but I would love to hear your thoughts on this!

**Comment by mikeyhew** [comment] 2019-06-05 22:00
>Another solution I thought of was changing the composition of the elements to something more logical, where the Connected component wraps the Autocomplete and the Select as its two children.

I looked into the implementation of connected components to, and I think something like this would be best. But in the short term, the easiest thing to do would be to add `connectedRight` and `connectedLeft` props to `Autocomplete`, and implement them by wrapping the `Autocomplete` component in a `Connected` component.

**Comment by dleroux** [comment] 2019-07-18 11:31
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Closed** 2020-01-21 12:33 UTC
Labels: Icebox, ⚗️ Development, 🌟 Autocomplete, 🐛Bug
