### ISSUE TITLE
Banner and FilterControl break React hydration

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/polaris-react#1283] opened 2019-04-08 15:45 UTC
# Issue summary
I've had to disable some SSR in an internal Shopify project because a couple of Polaris components don't have consistent IDs between server / client.

`Banner`'s unique ID helper is defined at module scope, and never resets on the server side: https://github.com/Shopify/polaris-react/blob/9aa2768d29d9548ac88728580340bfa42b8b7e1f/src/components/Banner/Banner.tsx#L182-L185

[`TextField`'s id factory](https://github.com/Shopify/polaris-react/blob/9aa2768d29d9548ac88728580340bfa42b8b7e1f/src/components/TextField/TextField.tsx#L120-L122) can be overridden, but FilterControl doesn't give callers control over this: https://github.com/Shopify/polaris-react/blob/9aa2768d29d9548ac88728580340bfa42b8b7e1f/src/components/ResourceList/components/FilterControl/FilterControl.tsx#L95-L110

## Expected behavior
* Banner should accept an id prop
* ResourceList should either accept an id prop and pass it on to `FilterControl` -> `TextArea` (or make everything magically work 😄)

## Actual behavior
Banners and ResourcesLists rendered server side hydrate properly on the first load after server startup.  Then fail to hydrate on every other page load.

## Steps to reproduce the problem
Message me, and I'll describe how to get an internal project into this state.

## Reduced test case
N/A because this needs a server.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.12.0
- Browser: all
- Device: Macbook Pro
- Operating System: Mojave 10.14.3

**Comment by alex-page** [comment] 2019-04-08 18:15
Thanks @GoodForOneFare for bringing this up. I'll have a look in the next day or two.

**Comment by alex-page** [comment] 2019-04-15 19:16
We probably just need to remove the ID from Banner as it's not used for any accessibility enhancements.

**Comment by GoodForOneFare** [comment] 2019-06-26 03:39
[`SearchField` now uses module-scoped unique ids](https://github.com/Shopify/polaris-react/blob/master/src/components/TopBar/components/SearchField/SearchField.tsx#L12) and now causes SSR warnings in web.

**Comment by CameronGorrie** [comment] 2019-06-28 16:34
<img width="841" alt="Screen Shot 2019-06-28 at 12 06 27 PM" src="https://user-images.githubusercontent.com/3865674/60355888-84e49980-999d-11e9-8243-a19c9a6e9beb.png">

**Comment by BPScott** [comment] 2020-01-04 01:41
Reopening this as SSR discrepancies are still an issue

**Comment by BPScott** [comment] 2020-01-04 01:41
ping @yourpalsonja, it'd be good for the backlog buddies to take a look at this and #1046

**Comment by chrisandrewca** [comment] 2020-01-11 05:23
Hi, I'm seeing a similar issue with ResourceList. The 'Showing x items' title is missing. The promoted action is also missing when configured.

`Warning: Prop `id` did not match. Server: "ResourceListItemOverlay11" Client: "ResourceListItemOverlay1"`

![1](https://user-images.githubusercontent.com/409078/72199269-808a4600-33ee-11ea-879c-475ab039130b.png)

Are you using the React components? (Y/N): Y
Polaris version number: 4.9.0
Browser: chrome
Device: desktop
Operating System: windows

Server side rendering: Y
Next.js

When I disable SSR for this scenario, the console error disappears but the title and buttons remain missing.

**Comment by BPScott** [comment] 2020-01-11 05:27
Probot. Stop that.

**Comment by KyleKilbride** [comment] 2020-01-30 16:35
Hey 👋

I am seeing an issue on Web (`/admin/marketing`) that I believe is related to this issue. Currently, in production, we are seeing out `loading` state appear briefly inside the Markup for the banner. 
<img width="382" alt="firey _ Aperçu du marketing _ Shopify 2020-01-30 10-29-21" src="https://user-images.githubusercontent.com/6219118/73469290-237e1200-4354-11ea-911d-e037632a95fd.png">

This is what it looks like briefly before it goes back to its normal state.
![](https://screenshot.click/30-44-fm4o1-e2h3h.png)

I cannot seem to replicate it locally unless we do a production build of Web. 

We are currently using a production build to see if there is anything we can do on Web to fix it there, but I thought I would ping here.

**Comment by BPScott** [comment] 2020-07-28 16:53
Still haven't found the time to polish this off. Waiting for the next version of react and replacing our useUniqueId hook with [`useOpaqueIdentifier` once it becomes stable](https://github.com/facebook/react/pull/17322) is gonna be the long term solution.

Components that don't yet use useUniqueId are tracked in https://github.com/Shopify/polaris-react/issues/1995

**Comment by BPScott** [comment] 2020-07-28 17:06
Actually, gonna close this as a duplicate of #1761 as that's got a more up-to-date state of the world

**Closed by BPScott** 2020-07-28 17:06 UTC
Labels: 🌟High Priority, 🐛Bug
