### ISSUE TITLE
Can not compile in another component 

### ISSUE THREAD

**Issue by tranvannhat** [Shopify/polaris-react#423] opened 2018-09-12 07:50 UTC
I wrote one particular component and used Polaris, but when the build error message as shown below, all other libraries are operating normally, Polaris own error, you can check it?
<img width="1435" alt="screen shot 2018-09-12 at 2 45 33 pm" src="https://user-images.githubusercontent.com/28804941/45410102-27e05700-b69b-11e8-9f5c-ddfd1d5224d7.png">

**Comment by chloerice** [comment] 2018-09-12 21:43
Hi @tranvannhat, thanks for raising this. Are you importing `classNames` in your component by chance? I'm not able to reproduce and it's unclear where the error is being thrown from. Can you share the full error message?

**Comment by chloerice** [comment] 2019-01-08 23:18
Closing this issue as we're unable to reproduce. Please reopen and provide any additional information you can if you are still experiencing this error.

**Closed by chloerice** 2019-01-08 23:18 UTC
