### ISSUE TITLE
Layout broken on consecutive AnnotatedSection within embedded app

### ISSUE THREAD

**Issue by w00kie** [Shopify/polaris-react#824] opened 2019-01-05 15:25 UTC
# Issue summary

So I have an embedded app within an AppProvider with apiKey set and when I try to get two consecutive AnnotatedSections the page is completely broken.

## Expected behavior

Get two consecutive AnnotatedSections that look like AnnotatedSections.

## Actual behavior

First I get a render of the page for a split second with the format of a standalone app and the layout looks good, like this:

![screen shot 2019-01-05 at 23 43 03](https://user-images.githubusercontent.com/56729/50725732-67004f80-1145-11e9-9cc8-48c77b8df1a6.png)

Then the AppBridge must kick in or something and the page re-renders with the embedded app format and my sections get all broken:

![screen shot 2019-01-05 at 23 44 25](https://user-images.githubusercontent.com/56729/50725750-ba729d80-1145-11e9-8713-0bb3bf99fd86.png)

## Steps to reproduce the problem

I notice that if I remove the primaryAction from my Page the layout is still broken but it's not as bad:

![screen shot 2019-01-06 at 0 21 36](https://user-images.githubusercontent.com/56729/50725939-30c4cf00-1149-11e9-827f-7fb044ef6f44.png)

See the misalignment of the cards and the missing separator between sections.

## Reduced test case

Since this only happens within a real embedded app, I can't really give you a code sandbox to reproduce it. But this is the skeleton of my React code:

```jsx
<AppProvider apiKey={API_KEY}>
  <ApolloProvider client={client}>
    <Page title="Title" primaryAction="">
      <Layout>
        <Layout.AnnotatedSection>
          <Card></Card>
        </Layout.AnnotatedSection>
        <Layout.AnnotatedSection>
          <Card></Card>
        </Layout.AnnotatedSection>
      </Layout>
    </Page>
  </ApolloProvider>
</AppProvider>
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.3.0
- Browser: Chrome v71
- Device: Desktop
- Operating System: Mac

**Comment by w00kie** [comment] 2019-01-06 04:10
Removing both `title` and `primaryAction` from the `<Page>` restores proper layout.

Is there a recommended way to get a Save button at the top of the page and not only bottom? The docs seem to imply `<PageActions>` should only be used at the bottom of the page.

**Comment by damianhodgkiss** [comment] 2019-01-06 04:12
Yep, I found the same, I am wondering if it works at all as it seems like such a common thing such as every page element would surely be noticed as broken.

Also contemplating not using the title, primaryAction or breadcrumbs for now but then lose some of the embedded app consistency features.

**Comment by w00kie** [comment] 2019-01-06 13:03
For my issue of putting a save button at the top of the page, I ended up having a `<PageActions>` at the bottom and then manually inserting a `<Button primary>` in a `<Card.Header>` on the first Card.

**Comment by vividviolet** [comment] 2019-01-11 20:41
@w00kie Can you try adding the `shopOrigin` to the `<AppProvider>`? For example:
```
<AppProvider apiKey={API_KEY} shopOrigin="shop1.shopify.com">
```

It's strange that your app is rendering first as a non-embedded app and then turning into an embedded app later. This might be due to the `shopOrigin` not being set correctly.

**Comment by damianhodgkiss** [comment] 2019-01-12 00:45
I am seeing the same behavior with shop origin set too.  Occasionally it will work as in render full then app bridge moves them up and it's okay but majority of time after app bridge moves them up it leaves it fubar.
Tried the app bridge 1.0.3 branch too.  Modal and toast are also not working.  Seems the only way to use an embedded app is disable appkey and let it run as a full app in which case everything works fine.

**Comment by damianhodgkiss** [comment] 2019-01-12 07:30
Definitely an SSR issue, I forced it to load AppProvider as a client-side module by making a local AppProvider.js as follows

```
import { AppProvider } from '@shopify/polaris';

export default AppProvider;
```
then forcing next.js to use this instead:

`const DynamicAppProvider = dynamic(() => import('../components/AppProvider'), { ssr: false });
`

I believe the problem is because AppProvider module isn't attempting to fix the appBridge in polarisContext in componentDidMount, however trying to add it still wouldn't run (nor would console or alert logs)

https://github.com/Shopify/polaris-react/blob/master/src/components/AppProvider/AppProvider.tsx#L43-L45

**Comment by vividviolet** [comment] 2019-01-12 07:55
Is this a regression? The SSR issue was  fixed in version 3.2.1: https://github.com/Shopify/polaris-react/issues/372#issuecomment-445575382

Cc @tmlayton

**Comment by hannachen** [comment] 2019-01-15 22:11
@vividviolet and I were able to reproduce the issue, but haven't found the root cause. This is what we observed:

For both working and non-working versions, the React nodes component structure is correct, meaning the issue is probably not with Polaris.

### Polaris React components
<img width="1133" alt="screen shot 2019-01-15 at 4 47 41 pm" src="https://user-images.githubusercontent.com/2709526/51212743-4a071180-18e7-11e9-8ffa-622093cd297c.png">

However, we're not sure how Next.js generates the markup, as the incorrect version doesn't match the React component structure.

#### Incorrect
The markup has the page content incorrectly nested inside `Polaris-Page-Header` and `Polaris-Page-Header__PrimaryAction`

| UI  | Markup |
|---|---|
| <img width="998" alt="screen shot 2019-01-15 at 4 51 16 pm" src="https://user-images.githubusercontent.com/2709526/51212495-a289df00-18e6-11e9-8155-18faadff7637.png"> | <img width="976" alt="screen shot 2019-01-15 at 4 48 38 pm" src="https://user-images.githubusercontent.com/2709526/51213227-73746d00-18e8-11e9-8c43-40f228794a25.png"> |

#### Correct
The markup has the page content correctly nested inside `Polaris-Page__Content`.

| UI  | Markup |
|---|---|
|<img width="979" alt="screen shot 2019-01-15 at 4 50 47 pm" src="https://user-images.githubusercontent.com/2709526/51212664-13c99200-18e7-11e9-8378-03c4345544ec.png">| <img width="1063" alt="screen shot 2019-01-15 at 4 50 39 pm" src="https://user-images.githubusercontent.com/2709526/51212673-1a580980-18e7-11e9-906f-b81271e3771c.png"> |

@tylerball any ideas on what might be going on with Next.js? We're expecting the page header to be removed, but the generated HTML is placed inside the header container instead.

cc: @nwtn

**Comment by damianhodgkiss** [comment] 2019-01-16 01:08
@hannachen I don't believe it to be a polaris problem specifically but more a side effect of a client side library and ssr.

when next.js renders the page, appBridge doesn't exist so the header is placed in the pre-rendered HTML so when its sent to the browser the title is seen in the browser and when appBridge is loaded on the client it then tries to (move it).. even if it was able to move it every time successfully, wouldn't this always result in a 'flicker' type situation as the pre-rendered HTML is always sent before appBridge is loaded.

I think to fix that polaris on SSR would need to be aware appBridge will be coming later and skip doing the full-app rendering in the meantime so it's omitted from the pre-rendered SSR HTML?

when next.js SSR first renders all the components appBridge is always going to be undefined: https://github.com/Shopify/polaris-react/blob/master/src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts#L30 so the header will always render in page first and result in a 'markup change' when appBridge does load.

**Comment by juliantrueflynn** [comment] 2019-01-31 20:45
I am also experiencing this issue with using Next.js and AppProvider. Styles are removed after initial render.

Here's the app I am working on that is experiencing this issue in case it helps: https://github.com/juliantrueflynn/conditional_welcome_bar/tree/fix__broken-ssr/client

Pictures below are in order of: initial load (when styles appear to work), and after load (styles removed).

![before](https://user-images.githubusercontent.com/2691129/52084103-4920e180-256f-11e9-8937-984fe4a6ac25.png)
![after](https://user-images.githubusercontent.com/2691129/52084106-4b833b80-256f-11e9-8eae-e8919b3075cb.png)

**Comment by vividviolet** [comment] 2019-02-04 17:15
@w00kie @damianhodgkiss @juliantrueflynn we're exploring a solution to this issue that will not require adding `forceRender` to the Page component. We'll keep you updated.

**Closed** 2019-03-15 21:06 UTC
Labels: App Bridge
