### ISSUE TITLE
Fix   do/don't layouts on mobile

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react#10614] opened 2023-09-21 17:11 UTC
![Image](https://github.com/Shopify/polaris/assets/6844391/346464df-89c8-49bb-8856-6386ba0f150a)

**Comment by tjonx** [comment] 2023-09-21 17:13
No need to open issues for ongoing issues

Duplicate of https://github.com/Shopify/polaris/issues/10020

**Closed as completed** 2023-09-21 17:44 UTC
