### ISSUE TITLE
[Page] Inside embedded app: show an action's loading state

### ISSUE THREAD

**Issue by andrewlo** [Shopify/polaris-react#946] opened 2019-01-29 21:14 UTC
# Issue summary

It seems like setting `loading: true` property in an Action (ex. primaryAction) a Page component in an embedded app doesn't show a spinner on the button.

This is a common use case when the primary button runs an API request.

## Expected behavior

When a Page action's loading property is true in an embedded app, it shows a spinner on the button.

## Actual behavior

It doesn't show a spinner

## Steps to reproduce the problem

1. Create an Embedded app using a Page with primaryAction and set `loading: true` on it
2. There isn't a spinner in the button

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.4.0
- Browser:
- Device:
- Operating System:

https://github.com/Shopify/app-bridge/issues/686

**Comment by sdn90** [comment] 2019-02-20 06:49
I've noticed the same issue for any App Bridge component with actions.

From what I've found looking through the files from the app-bridge package, it seems like the `loading` option isn't implemented for buttons.

Can someone shed some light on whether this is supposed to be working or if its planned for the future?

**Comment by vict-shevchenko** [comment] 2019-06-03 08:55
Just wanted to add one comment, when similar steps are done during development (not in embedded app) spinner is displayed well.

**Comment by chloerice** [comment] 2019-10-09 17:21
Closing as this is a duplicate of https://github.com/Shopify/polaris-react/issues/272

**Closed by chloerice** 2019-10-09 17:21 UTC
Labels: App Bridge
